AWSTemplateFormatVersion: '2010-09-09'
Description: Root template to visualize all stacks together.

Resources:
  NetworkStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./network-stack.template.yaml

  SecurityStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./security-stack.template.yaml
      Parameters:
        VpcId: !GetAtt NetworkStack.Outputs.DevVPC
    DependsOn: NetworkStack

Metadata:
  AWS::Composer::Groups:
    Group:
      Label: Group
      Members:
        - NetworkStack